# Generated by Django 4.2.10 on 2024-03-16 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0004_attendance_subject_attendance_report_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faculty",
            name="admin",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
