# Generated by Django 4.2.10 on 2024-03-17 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("dashboard", "0008_alter_attendance_id_alter_attendance_sub_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="sub_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="dashboard.subject"
            ),
        ),
        migrations.AlterField(
            model_name="attendance_report",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="attendance_report",
            name="student_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="dashboard.students"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="groups",
            field=models.ManyToManyField(
                related_name="custom_user_groups", to="auth.group"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="user_permissions",
            field=models.ManyToManyField(
                related_name="custom_user_permissions", to="auth.permission"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[("1", "HOD"), ("2", "Faculty"), ("3", "Student")],
                default=1,
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="sessionyearmodel",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="subject",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
